// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OsTresMotoqueirosDoApocalipseVerde.Infraestructure;

#nullable disable

namespace OsTresMotoqueirosDoApocalipseVerde.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519010723_Create tables Motorista and Motos")]
    partial class CreatetablesMotoristaandMotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MotoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("MotoId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MotoId")
                        .IsUnique();

                    b.HasIndex("MotoId1")
                        .IsUnique()
                        .HasFilter("\"MotoId1\" IS NOT NULL");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Motorista", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Moto", "Moto")
                        .WithOne()
                        .HasForeignKey("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Motorista", "MotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Moto", null)
                        .WithOne("Motorista")
                        .HasForeignKey("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Motorista", "MotoId1");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entities.Moto", b =>
                {
                    b.Navigation("Motorista")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
